"""Compatibility entry point for manuscript field/error plotting.

All formal absolute-error maps, local-region metrics and calibration figures
are generated by benchmark_evaluate.py using one consistent configuration.
"""
from benchmark_evaluate import main

if __name__ == "__main__":
    main()
